name: firebase_practice_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_analytics: ^10.8.7
  firebase_core: ^2.25.5
  provider: ^6.1.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
flutter:
  uses-material-design: true

